<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Include>[Results]*</Include>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TngTech.ArchUnitNET" />
		<PackageReference Include="CsCheck" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Architecture.Testing\Architecture.Testing.csproj" />
		<ProjectReference Include="..\..\src\Results\Results.csproj" />
	</ItemGroup>

</Project>
